apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wowzas.wowza.example.com
spec:
  group: wowza.example.com
  names:
    kind: Wowza
    listKind: WowzaList
    plural: wowzas
    singular: wowza
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
